title:              Alitrack ML
email:              smartanonymousprof13@gmail.com
description:        Machine Learning
author:             Steven Lee
baseurl:            "/jekyll"
url:                "https://alitrack.github.io/jekyll/"

# Social Profiles
twitter_username: alitrack
github_username:  alitrack  
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
